### ISSUE TITLE
trying to install on void linux with creats.io, requires systemd

### ISSUE THREAD

**Issue by ronniedroid** [leftwm/leftwm#100]
I don't understand why would a WM depend on an init system?

**Comment by lex148** [comment]
Ugh, This is from the logging library we are using. You are 100% correct it SHOULDN'T. Let me see if I can replace it.

**Comment by lex148** [comment]
This was being caused by our use of _slog-journald_. Logging to journald is great for the people that want it, but I agree it shouldn't by on be default. I have moved this into its own feature that must be turned on to use.
```
cargo build --features=journald
```
I am not ready to make another release to crates.io yet, so you are going to need to build from source to get this working on void.

**Comment by ronniedroid** [comment]
Thank you very much for taking quick action.

**Comment by nihilismus** [comment]
I successfully installed `leftwm` from GitHub with `rustup` & `cargo` in Void Linux using: 

```bash
$ cargo install --git https://github.com/leftwm/leftwm --branch master --force
```

Binaries ended up  being installed in `$HOME/.cargo/bin`.
