### ISSUE TITLE
Allow disabling the cursor repositioning on window resize

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#1011]
> **Note**: I'm creating this issue preemptively, it is not yet approved for implementation. Please comment and thumbs up if you wish to see this setting.

### Describe the enhancement

Implement a `disable_cursor_reposition_on_resize` (or something shorter) configuration that allows disabling the cursor reposition to the windows' bottom-right during resize.

This is a follow-up on #1003 and #1009

### How important is this enhancement to you?

It is just an idea

### How important do you think is this enhancement for the average LeftWM user?

I don't know, may be a niche edge-case

**Comment by 0323pin** [comment]
Maybe!?
Rebuilt `leftwm` today and it's a really nice feature. One less reason to use the trackpad. Don't see why I would disable it.

`SwapWindowTop` is also nice, I'm glad I'm running along the latest commits 😄

**Comment by BKSalman** [comment]
I think it's kinda annoying for the cursor to reposition, because it kinda breaks the flow of having to resize to show something hiding, then having to move the mouse to reach it, even tho the mouse was already on top of it

and also I'm used to resizing in multiple rather than dragging the whole thing in one go (I know I'm weird, but I swear it's really annoying)

I can create a PR for this, since I want this feature

**Comment by BKSalman** [comment]
I think this issue can be closed (?) since #1123 got merged :)

**Comment by VuiMuich** [comment]
Ah, I didn't pay attention to your exact wording, just saw the issue mentioned and thought it would be auto-closed.

**Comment by BKSalman** [comment]
> thought it would be auto-closed

ye, I thought that too, I guess I needed to say "resolves #whatever" so github picks up on it

**Comment by VuiMuich** [comment]
yeah `resolves` and `closes` should work. Idk if there is a list of keywords that work somewhere...
