### ISSUE TITLE
Focus disappears when removing several windows at a time

### ISSUE THREAD

**Issue by FrBst** [leftwm/leftwm#1204]
### Describe the bug

When `sloppy_mouse_follows_focus = false` or `focus_behaviour = driven`. If I try to create and then close multiple windows while mouse cursor stays on another window or on a screen border, focus disappears after removing two of the windows. After that, FocusWindow and CloseWindow bindings do not work until I move mouse to refocus a window or switch workspaces.

System journal doesn't have any errors.

### Steps to reproduce (optional)

Source code from tag `0.5.1`, config file from `examples/config-with-comments.ron`, and same happened on `master`
1. Set `sloppy_mouse_follows_focus: false`
2. Move mouse to the left side of the screen and open multiple terminals repeatedly
3. Try to close the terminals using keybinding, focus should disappear after closing second window

### OS / Distro

Arch linux

### Additional System Information (optional)

```text
Built from source, git tag `0.5.1`
```

### LeftWM Check

```text
:: LeftWM version: 0.5.1
:: LeftWM git hash: 0.5.1
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found.
```

**Comment by barkyq** [comment]
I have a similar problem: if I have `emacsclient` and `alacritty` open in the same tag, with focus on the `emacsclient`, and I close the `emacsclient`, the focus is lost, even though there is only one remaining window in the tag.

I am using `ClickTo` and so the only way to regain focus is to click on the sole remaining window. `FocusWindowUp` and `FocusWindowDown` keybindings do nothing.

**Comment by barkyq** [comment]
cf #1145 and #1108

**Comment by paul-ohl** [comment]
Exact same issue here!

**Comment by chaulkie** [comment]
My workflow has been frustrated by this too. It seems to stem from the refocus behaviour; when you close a window, focus will move to the previously focused window. If you have closed the previously focused window, the logic gives up and doesn't focus on anything.

A similar thing happens when I change to a tag with multiple windows, then close the window I land on. Instead of changing focus to the remaining window, focus is lost altogether, presumably because the previously focused window is on a different tag.

Besides the fact that the current behaviour causes this bug, I find it generally inconvenient, for example if I'm working with multiple workspaces. Much more sensible in my mind would be for focus to simply move up the stack of the current workspace.
