### ISSUE TITLE
improve `tag` focussing options for multi workspace configurations

### ISSUE THREAD

**Issue by lengyijun** [leftwm/leftwm#130]
I use polybar theme and I have two monitor.
Two things confused me:
1. Two workspace share the same polybar. I think leftwm should create two polybar automotically
2. When I switch between tags and monitors, sometime a window will move to another monitor

Are they the features of leftwm?

**Comment by lex148** [comment]
1)
How polybar is configured is entirely up to the theme. LeftWM doesn't even know polybar exists. 

There is a default theme that comes shipped with LeftWM that uses polybar. It creates a polybar for each screen, so it might be a good place for you to look. 
[https://github.com/leftwm/leftwm/tree/master/themes/basic_polybar](https://github.com/leftwm/leftwm/tree/master/themes/basic_polybar)

2) 
I believe what you are seeing here is the way LeftWM handles changing between tags.
Say you have tag [1][2] on monitor (a)(b) and your cursor is currently focused in monitor (b)

If you press Mod-1 you are telling LeftWM you want tag [1] to be displayed on monitor (b). This effectively steals tag [1] from monitor (a) and monitor (a) no longer has a tag to render. LeftWM then looks at the list of tags to fill into monitor (a) . It sees that tag [2] as the last one that was displayed and is no longer displayed. It then puts tag [2] on monitor (1).

The end result of all this is it appears as if the two monitors have switched places. 


Hope this helps,
-Lex Childs

**Comment by lengyijun** [comment]
Thx. I got it.
But it seems different from other tiling window managers.
As far as I know, i3 and awesome don't work like this. A window on one monitor seldom flies to another monitor.

**Comment by carrascomj** [comment]
Different WM do it differently. Xmonad manages screens like leftwm (they share all workspaces). I personally like it this way.

**Comment by mkubasz** [comment]
Yeap, the best, in my opinion, way to manage a bar. I mostly use xmonad so it is easier to switch between them.

**Comment by lfkrapp** [comment]
I agree that it is confusing but it is also inefficient.
1. The effective real estate density that you get is # tags / # monitors. The more monitors you have, the more tags you need. The more tags you have, the more things you have to remember. If you have a few monitors, this is not an issue.
2. Unless you are always doing the same thing, the named tag system doesn't fit well with a real case workflow. It is difficult to estimate how to allocate your tags beforehand. Maybe you are working on your code on the "Code" workspace and somebody asks you to fix a small bug on another code. Now, you need a second "Code" workspace because you don't want to close the first one.

In my opinion, giving the tags a tree-like structure e.g. separated tags per workspace is more efficient.

1. You can have a higher density without the higher search complexity in the same way as a search algorithm is more efficient on a tree structure. You just need to remember on which screen you put your browser, not the exact tag.
2. I see tags in a similar way as tabs in a browser. You don't know how many tabs you are going to open. Less is better but it is always nice to have the option to be able to open as many tabs as you like.

That said, I tried multiple WM, and leftWM is currently my favorite one (rust, toml config, choice of status bar). I tried it for a couple of weeks and really wanted to use it long-term but the tag system was a deal-breaker. So, I went back to dwm which is good but suckless is a utopistic view of software. Simple tasks require simple software but simplicity without extensibility and flexibility will not age well.

**Comment by drager** [comment]
Yeah, I think it's pretty confusing. Would be awesome if you'd be able to choose the behavior in configuration or something. I mean, I don't want my windows to move anywhere until I tell the WM to do so.

I also agree with @lfkrapp that leftwm is great! Rust, toml and be able to use whatever bar. However, I'm coming from dwm and awesomewm and don't want to go back...

**Comment by max-sixty** [comment]
Is this the same issue as https://github.com/leftwm/leftwm/issues/330? And solved with @AeroNotix 's [comment](https://github.com/leftwm/leftwm/issues/330#issuecomment-875490997)

**Comment by VuiMuich** [comment]
> Is this the same issue as #330? And solved with @AeroNotix 's [comment](https://github.com/leftwm/leftwm/issues/330#issuecomment-875490997)?

I believe #330 was a follow up to drager's comment here, so, yeah, kind of the related.

But AeroNotix' comments were basically a different issue.
 What `disable_current_tag_swap = true` is disabling the following behaviour:
 if you switch from `tag 1` to `tag 2` and you use your `Mod+2` (assuming default keybinds) leftwm will switch back to `tag 1`

The difficulty with #130 bullet 2 and #330 is (as I tried to explain in my last comment on #330) that this behaviour is at the core of leftwm and therefor not as easy to change as one might assume at first glance.
Maybe we should promote this principle as a core feature more and more prominently in the introductory section in the readme.

**Comment by max-sixty** [comment]
Thanks @VuiMuich ! I see now — the `disable_current_tag_swap` only applies to hitting `Mod+2` while workspace-2 is focused.

Is there a way of configuring leftwm to change the focus rather than swap the tags? i.e. taking @lex148 's example above:
- Say you have tag [1][2] on monitor (a)(b) and your cursor is currently focused in monitor (b)
- If you press Mod-1 you are telling LeftWM you want ~tag [1] to be displayed on monitor (b)~ to switch focus to tag [1], so your cursor focuses on monitor (a)
- If instead tag [1] was on monitor (c), _then_ it would move tag [1], since it wouldn't be possible to focus on tag [1] without the move.

**Comment by VuiMuich** [comment]
Ok I guess this might work:

We could introduce a command `FocusWorkspaceWithTag` which takes a `Tag ID` as it's value. 

If the destination tag is not visible it will `GoToTag` on the currently focused workspace. 
This could also be toggled by a config option `bool: auto_gototag_when_hidden` (better name welcome).

**Comment by hertg** [comment]
@VuiMuich Your proposal sounds great and seems to be well received, can you rename the issue to better describe what needs to be done?

**Comment by VuiMuich** [comment]
I am not sure if we wouldn't have nicer possibilities now.
A thing I wanted to explore for several other opportunities was if we can actually implement a `partial config load` and with that a command to toggle boolean fields of the config directly.

Renaming the title makes sense nevertheless.

**Comment by hertg** [comment]
Ok, sounds interesting.
If we introduce something that makes this issue obsolete, we'll close it. For now I think it's good to leave open :)
