### ISSUE TITLE
How to use XF86... keys?

### ISSUE THREAD

**Issue by MiraculousMoon** [leftwm/leftwm#131]
like this:
![图片](https://user-images.githubusercontent.com/61657399/96137558-5e01fc00-0f2f-11eb-80ba-beb278d700e5.png)

**Comment by lex148** [comment]
I would recommend using the config file in $HOME/.config/leftwm/config.toml 

It fully supports XF86 keys. Something like this is probably what you are looking for.
```
[[keybind]]
command = "Execute"
value = "vlc https://i.imgur.com/MxAE8Wp.mp4"
modifier = []
key = "XF86XK_AudioPlay"
```

You will want to run your own command like pactl instead of vlc 

Please note that in order to trigger XF86 keys most keyboards require you to press the `fn` key even though its not listed as a modifier in the example above.

Here is a list of all Keys LeftWM knows about and there names in LeftWM. 
[https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs](https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs)

Hope this helps,

-Lex Childs

**Comment by MiraculousMoon** [comment]
> I would recommend using the config file in $HOME/.config/leftwm/config.toml
> 
> It fully supports XF86 keys. Something like this is probably what you are looking for.
> 
> ```
> [[keybind]]
> command = "Execute"
> value = "vlc https://i.imgur.com/MxAE8Wp.mp4"
> modifier = []
> key = "XF86XK_AudioPlay"
> ```
> 
> You will want to run your own command like pactl instead of vlc
> 
> Please note that in order to trigger XF86 keys most keyboards require you to press the `fn` key even though its not listed as a modifier in the example above.
> 
> Here is a list of all Keys LeftWM knows about and there names in LeftWM.
> https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs
> 
> Hope this helps,
> 
> -Lex Childs

Thanks for you rapid reply. It works!
