### ISSUE TITLE
Polybar tray not clickable

### ISSUE THREAD

**Issue by sillen102** [leftwm/leftwm#138]
When I use any theme with polybar the icons in the tray are not clickable. Nothing happens when I click on them. I also have i3 installed on my machine and when I run polybar in i3 everything works fine. The widgets such as the clock are clickable though.

I also tried killing polybar and start with the config I use in i3 but I get the same result. The icons are there but nothing happens when I click them.

The same happens when I try to run polybar with the default config `polybar -c /usr/share/doc/polybar/config example`

I can get it to become interactive by adding `override-redirect = true` however when I do that the windows aren't aligning with it. The windows end up partially below the bar.

**Comment by sillen102** [comment]
With some more testing I can say that the workspace switcher is not clickable either. I haven't run lemonbar before but I tried it too and on lemonbar nothing is clickable. Is that normal for lemonbar?

**Comment by sillen102** [comment]
I think this problem is some kind of timing problem. If I restart LeftWM eventually polybar will become responsive.

I also tried disabling the template.liquid file that was present in the themes I tried and then I got no workspace indicator of course. However if I restored the file without reseting LeftWM the workspace switcher came to life and was clickable!

**Comment by KevinNThomas** [comment]
Hello, in my case https://github.com/leftwm/leftwm/pull/150 did not fix this issue, polybar elements are still not clickable unless I set `override-redirect = true` in the polybar config, but then the window manager ignores the bar like @sillen102 said.

**Comment by piotrmaks** [comment]
@KevinNThomas would you mind building and running LeftWM from https://github.com/leftwm/leftwm/pull/161? It's still WIP but one thing that may cause some trouble is connecting to xlib from multiple threads - which is removed in above PR.

**Comment by KevinNThomas** [comment]
Hi @piotrmaks, thanks for your work. Unfortunately, I built and ran LeftWM from the branch on your PR and the polybar icons are still not clickable, and it also made my WM really laggy (delay when opening windows, and jitteriness when moving around windows with the mouse).

**Comment by diegobfernandez** [comment]
I was having the same issue until I found out that removing the xwindow module to present the title would make the bar clickable again.
Looking through polybar issues I found this one: https://github.com/polybar/polybar/issues/1490
There they say it's about how the WM is handling the bar as it's a normal xwindow. Sorry if I said something wrong, I am fairly new to the Xorg/WM/Polybar world and I am not sure if I got everything correct.

I don't want to have an extra transparent bar just for the sake of this. Since this is not my main box I am ok with not having the title, but as I pretend to move to leftwm + polybar in the future as my main workplace it would be nice to have the window title working.

Please let me know if I can help with anything to fix this.

**Comment by mautamu** [comment]
Hmm, maybe when we get a dock we should tell the DM that we intend to unsubscribe from the bar events (but keep track of it somehow?). 
Will need to look to see if there is an easy way to pass events to the bar while subbed.
