### ISSUE TITLE
Weird startup banners: Libreoffice, gimp, krita, cura, etc.

### ISSUE THREAD

**Issue by carrascomj** [leftwm/leftwm#154]
### Description

Programs like the ones listed in the title show a banner at startup. They are displayed "funnily". For instance:
![image](https://user-images.githubusercontent.com/46683255/103692017-749c7a00-4f97-11eb-8dd8-6fe219b73caa.png)

In the case of krita or cura the banner is showed in the left corner.

### Expected behavior

I believe a good default would be to have these type of "banners" displayed floating at the center. I think other tiling WMs do it without user intervention, but I don't know if they are hardcoded somehow or there is some information that the WM can use to recognise these types of windows.

**Comment by mautamu** [comment]
Good evening @lex148,

 What's the best way to get the XYHW that the program asked for and pass that to the window handler? 7fd13ad kinda resolves the issue for me (the splash screen no longer covers the whole screen), but I'd like to give the splash screen the size it asked for so that it doesn't tile. What do you suggest?

Best,
Mautamu
