### ISSUE TITLE
Change default value of the modkey+shift+x keybind

### ISSUE THREAD

**Issue by midnightexigent** [leftwm/leftwm#288]
The default value of that keybind is `pkill leftwm`, the problem is logging back in after that can create zombie processes, notably processes started in `.xsession`

I wanted to suggest to replace the default with: `loginctl kill-session $XDG_SESSION_ID`

**Comment by VuiMuich** [comment]
I believe loginctl is part of systemd, right?

In order to keep the defaults as free as possible from any distro dependent commands I'd suggest to have a **nb** in the documentation to strongly suggest the use of loginctl.

Another possibility would be to have a routine similar the one setting the default terminal to determine the default logout procedure, that defaults to pkill in absence of systemd.

**Comment by midnightexigent** [comment]
Actually, I don't use systemd (I run Artix linux with openrc). 

I believe that distros that don't run systemd have [elogind](https://wiki.gentoo.org/wiki/Elogind) to manage sessions which provides a similar interface to systemd's loginctl

**Comment by mautamu** [comment]
One middle ground we might consider is similar to that of the terminal command: if loginctl is in the path (or is there a way to know leftwm was started from there?) then use loginctl, otherwise default to pkill and give a warning in leftwm-check.
