### ISSUE TITLE
session doesn't close fully

### ISSUE THREAD

**Issue by nathanleighsays** [leftwm/leftwm#31]
Running leftwm with SDDM, when you restart SDDM and then start a new session in Plasma, the windows are stuck in a bizarre forced tiling situation that persists until a full reboot.

**Comment by lex148** [comment]
Wow you found a real treasure of a bug in this one. I'm working right now to get this one fixed, but so it doesn't block you in any way you can avoid it by killing leftwm to logout instead of SDDM

Something like "pkill leftwm" should do the trick.

Expect to see a fix for this in the next release for sure.
