### ISSUE TITLE
Windows when reloading Left

### ISSUE THREAD

**Issue by nilq** [leftwm/leftwm#33]
After having moved windows out of their grid places, running _Mod + shift + R_, they reset their positions and lock to the tiling grid again.

**Comment by lex148** [comment]
Thanks for reporting this bug! I just pushed a fix for this but there is a little more you need to know. 

LeftWM now has two ways to do the reloading a HardReload and a SoftReload. Because your config was created before this fix you will need to change it from HardReload to SoftReload in the file ~/.config/leftwm/config

Please change the section:
[[keybind]]
command = "Execute"
value = "pkill leftwm-worker"
modifier = ["modkey", "Shift"]
key = "r"

To: 
[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

This fix will be in the next release. I'm going to try to squeeze one more bug fix in before the next release, but expect it Sunday or early in the week. If your using latest from github just pull latest instead.
