### ISSUE TITLE
Feature request: Be able to configure window swtiching behavior

### ISSUE THREAD

**Issue by drager** [leftwm/leftwm#330]
Hello!

As far as I understand it, switching between tags and monitors, will sometimes move a window to another monitor.

I'm wondering if it would be a good idea (might be hard to implement?) to be able to configure the behavior of leftwm regarding this window switching.

**Comment by VuiMuich** [comment]
This would definitely be a nice config option along with a command to `set on`/`set off`/`toggle`

**Comment by drager** [comment]
Is this someone wants to implement? Or perhaps point towards a direction on where to start. Personally I do not have that much experience of implementing window managers, but with some pointers I could try myself of course.

**Comment by paulhersch** [comment]
so you mean instead of moving windows of the tag you switched to to the focused screen, you want to move the focus to the one screen that has the tag on it?

**Comment by AeroNotix** [comment]
Came here to make an issue for this.

I just want the Xmonad behaviour. Unsure of the leftwm-specific lingo (seems there are as many WM dialects as there are WMs), but I will try:

* M-{1,0} are bound to selecting which virtual desktop I have on the screen I have focused.
* If I tap M-{1,0} multiple times, it rotates between two virtual desktops.
* How do I stop this behavior?

**Comment by drager** [comment]
> so you mean instead of moving windows of the tag you switched to to the focused screen, you want to move the focus to the one screen that has the tag on it?

I simply want "no magic". It should be as I put it. No auto-magic moving of my windows.

**Comment by AeroNotix** [comment]
If the current LeftWM implementation doesn't support disabling this then I'm more than happy to roll my sleeves up and attempt to implement.

**Comment by AeroNotix** [comment]
Ah! Reading the source code a little to try to find it. I saw "disable_current_tag_swap". Again, the myriad lingo in use makes it harder to understand from documentation, but reading the source makes it clear.

`disable_current_tag_swap = true` provides the behaviour I am seeking.

**Comment by VuiMuich** [comment]
> > so you mean instead of moving windows of the tag you switched to to the focused screen, you want to move the focus to the one screen that has the tag on it?
> 
> 
> 
> I simply want "no magic". It should be as I put it. No auto-magic moving of my windows.

Despite my initial agreement, I have to say it is kind of contradicting leftwm's idea of workspace handling.
And in fact the logic is quite simple just not necessarily intuitive if you came from a different concept and possibly needs better documentation. 
It basically goes like this:
ws1 is on tag1 and ws2 is on tag3
When ws1 switches to tag4 ws2 stays on tag3
When ws1 now Switches to tag3 and ws2 switches to tag4
When ws1 now switches to tag2 ws2 stays on tag4.

Very basic: when you call a tag that is currently displaying on another workspace they swap. If the called tag is nowhere displayed before it just switches to the tag on the current workspace.

Unlike most other WMs, which use a full set of workspaces for each display, leftwm uses the same tags on all workspaces and workspaces can either be displays or regions of displays.
Therefore we use workspace/tag terminology instead of display/workspace.

The question is: is it possible at all and if so is it desirable to show the same tag on multiple workspaces?
I believe this might be very hard to handle gracefully. 

I have to admit it confused me quite a bit when I was new to leftwm, but after getting used to it I wouldn't want to have it any different anymore.
