### ISSUE TITLE
Strange behavior with certain (invisible?) windows

### ISSUE THREAD

**Issue by orclev** [leftwm/leftwm#394]
**Describe the bug**
Certain types of windows seem to go invisible when being "closed" and continue to take up space in desktop layouts even though there is no visible window present. I've seen this with a few applications, but where it shows up most readily is with the Jetbrains Toolbox application. This app is meant to be a systray helper that's used to update, manage, and launch other Intellij applications. After opening the toolbox, even after closing it, it continues to take up a slot in the current layout even though there's no visible window. I can use the various keyboard shortcuts to move the other windows on the workspace around, and they'll push the "empty" slot around the workspace.

Considering the other issues with things like some apps just not showing up in the systray, or dialogs appearing in strange places, I suspect there's also some kind of window parenting issue at play as well that might be related to this issue.

**To Reproduce**
1. Have a layout like main and vert stack selected
2. Install Jetbrains Toolbox
2. Open Jetbrains Toolbox
3. Close Jetbrains Toolbox window
4. Open two terminals
5. Observe that the terminals do not appear in the expected location, with one empty position always appearing in the layout.

**Expected behavior**
After closing Jetbrains Toolbox it should no longer take up a slot in the workspace layout.

**Screenshots**
![2021-06-19-054136_1920x1080_scrot](https://user-images.githubusercontent.com/60914/122638447-23ee8880-d0c2-11eb-8c06-33ebfb087daa.png)
![2021-06-19-054204_1920x1080_scrot](https://user-images.githubusercontent.com/60914/122638451-281aa600-d0c2-11eb-8fc8-9a79c9f4c563.png)
![2021-06-19-054221_1920x1080_scrot](https://user-images.githubusercontent.com/60914/122638455-2a7d0000-d0c2-11eb-9fe9-33ce1392465b.png)

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`
```
:: LeftWM version: 0.2.8
:: LeftWM git hash: e376938
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
```

**Additional context**
Actually quitting the toolbox (via the systray icon, or using kill) rather than simply closing the window frees up the spot in the workspace. Once the window has been closed, attempting to re-open the window using the systray icon produces no result. Once the window is closed, it's gone for good and requires restarting the app to return it to functioning.

Using xwininfo and xprops this is what I could find out about the window after it has been closed and entered the broken state:
```
xwininfo: Window id: 0xc00007 "JetBrains Toolbox"

  Absolute upper-left X:  962
  Absolute upper-left Y:  558
  Relative upper-left X:  962
  Relative upper-left Y:  558
  Width: 942
  Height: 506
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 2
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +962+558  -12+558  -12-12  +962-12
  -geometry 942x506-12-12
```
xprop:
```
_NET_WM_DESKTOP(CARDINAL) = 7
_NET_WM_STATE(ATOM) =
_NET_WM_USER_TIME(CARDINAL) = 315788256
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 440 by 700
		program specified maximum size: 440 by 700
WM_CLASS(STRING) = "JetBrains Toolbox", "jetbrains-toolbox"
WM_NAME(STRING) = "JetBrains Toolbox"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 181445
WM_CLIENT_MACHINE(STRING) = "hogfather"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

**Comment by VuiMuich** [comment]
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
```
This looks suspicious to me. If JetBrains launches and registers as `normal` window of course it reserves the space a tiled window would take, but if it then 'closes' its window only to the tray this would not free the tile.
Or am I getting something wrong here?

Is there a way to register JetBrains as another window type? like `utility` or `dialog`?

**Comment by AethanFoot** [comment]
I think this is probably the call they are using to hide the window (probably XUnmapWindow or something). I need to do a few bits when I have time, but if someone wants to have a look I can point you in direction.
Currently within event_translate.rs if the call is an UnmapNotify but this call is not a send event, we ignore it (relevant function is from_unmap_event). I haven't tested why this is (added before I found this project), so this may have some side effects with the current setup. I think the call gets spammed a lot (well unmap events seem to happen to windows randomly and don't actually hide the windows at times). One idea I had was to connect the Unmapping with our visibility system, e.g. use Unmap as the backend, however this might not work if not all calls to Unmap are to actually hide the window and not close it. If any time unmap is called that the idea is to just hide the window I can't see any other issue with this, and it would create a method of hiding windows instead of just moving the window of screen.
If anyone does want to try this before I have time I am happy to answer any questions or give any pointers that might help, if no one else has the time I should be able to start a few bits on wednesday if not tuesday.
Thanks!

**Comment by orclev** [comment]
Just updated and confirmed this fixes the issue. Thanks for the fast turn around!
