### ISSUE TITLE
[Question] Always spawn apps on a specific tag

### ISSUE THREAD

**Issue by pslobo** [leftwm/leftwm#427]
Hi, 

I'm not sure if this has been brough up yet or not. Is it possible (if not, is it planned), to spawn an app always on the same tag? For example, say I want Firefox to always open on tag "web", thunderbird, slack etc. to open on tag "comms". 

A possible workaround for now could be what is mentioned here: https://github.com/leftwm/leftwm/issues/76#issuecomment-598462605

**Comment by mautamu** [comment]
It depends on #292 and #165, but has not been fleshed out very thoroughly (see things that link to 165 for more info).

**Comment by carrascomj** [comment]
I implemented it on a fork https://github.com/carrascomj/leftwm/tree/feat-phf-wmclass

Considerations:

1. Maybe a PR should wait for https://github.com/leftwm/leftwm/pull/292
2. I am using a [`phf::Map`](https://github.com/carrascomj/leftwm/blob/feat-phf-wmclass/leftwm-core/src/handlers/window_handler.rs#L14) instead of reading from config (just for my own convenience for now, this should change).
3. Added the `WM_CLASS` attribute to the [`Window`](https://github.com/carrascomj/leftwm/blob/feat-phf-wmclass/leftwm-core/src/models/window.rs#L78) struct. The same can be done on the `Window.name` (I tried, it works fine) without adding anything, although `WM_CLASS` seems more general than the name.

**Comment by VuiMuich** [comment]
Had a look at it in the "create pul-request" dialogue of github and I think you could at least open it as a `draft PR`.
You could just add the logic to `leftwm-core`and leave out your `phf` config logic and someone else could add the config part to the `leftwm` crate.
I agree, the window name could be added later if the demand arises, as the window class should be sufficient for implementation of all these regular requested feats.
Waiting for #292 would not be necessary, as this should not break any existing config, when it is implemented as type `Option<>`.

---

Just for reference here a proposal for syntax in `config.toml`:
```toml
[[window_config_by_class]]
wm-class = "qutebrowser"
spawn_on_tag = "www" #tag.id as in the tag-configuration array, this could optionally be an integer with the tag.index
spawn_floating = true
```
or for multiple items:
```toml
window_config_by_class = [
    {wm-class = "qutebrowser", spawn_on_tag = "www", spawn_floating = true},
    {wm-class = "discord", spawn_on_tag = 7}
]
```

**Comment by carrascomj** [comment]
Regarding https://github.com/leftwm/leftwm/pull/630/files#diff-5935205e940079b06caaefb4fe34e6e7b6cd95d100adb4520c1e6ca83ef0d88bR254

Should special windows like `Splash` and `Dialog` with a predefined tag (by `WM_CLASS`) spawn on the focused workspace/tag or on the actual predefined tag? I'd say on the predefined tag (current implementation on PR) but not super sure about this one.

Working with krita, which spawns dialogs with the same `WM_CLASS` than the main window (as should be expected, I believe), the behavior seems correct. In this scenario, the focused tag is the predefined tag anyways, unless you try really hard to change it on time. However, there may be some edge cases that I'm not considering.

**Comment by VuiMuich** [comment]
I agree, if the splash provides the correct `WM_CLASS` the splash should directly spawn on the target tag. Otherwise it might be confusing.

For a moment I was thinking, if spawning it on current and moving it after a few secs would be elegant in order to give some visual feedback, but I guess this would be confusing as well.

**Comment by hertg** [comment]
> Should special windows like `Splash` and `Dialog` with a predefined tag (by `WM_CLASS`) spawn on the focused workspace/tag or on the actual predefined tag? I'd say on the predefined tag (current implementation on PR) but not super sure about this one.

It shouldn't always spawn on the predefined tag. I had this behavior for a while back when I was using `dwm` and it was quite annoying. When I moved the Firefox window away from my `surf` tag, any kind of popups (eg. picture-in-picture windows, file save as...) still spawned on the `surf` tag, and therefore out of my view, which was never my intention. I remember being able to mitigate the issue by explicitly creating a separate rule, specifying that picture-in-picture should not open on a specific tag. The problem was a very frequent one, not because I moved Firefox out of the predefined tag a lot, but because I set Firefox as "sticky` a lot, so that it appears on every tag.

I don't see a use-case where a popup of a currently visible window should open on a tag that is out of view. In my experience this usually led to the undesired behavior where the main window can no longer be interacted with (Try clicking `Save Page As` in firefox, move the popup away without closing it and try interacting with the main window, it won't accept any inputs/clicks).

Would be great if rules can also be created based on `instance` or `window-title`, similar to what is possible in `dwm`. See [my config](https://github.com/hertg/dwm/blob/master/config.def.h#L47-L49) for the before-mentioned example use-case.

I don't have much time this week to check out your PR, but the window-rules feature is something that I'm very looking forward to, so thanks for working on that! :heart:

**Comment by carrascomj** [comment]
That's the kind of edge cases that I was thinking about. It seems like for this to be perfectly usable it's important to allow the user to have more fine-grained control, specifying `instance` or `window-title` like you said (or even they type of the Window), most likely extending the config to look more like what @VuiMuich proposed.

> I don't have much time this week to check out your PR, but the window-rules feature is something that I'm very looking forward to, so thanks for working on that! :heart:

You're welcome! I have been missing this feature from when I was using xmonad, I hope it can be raised to a solid state soon.

**Comment by carrascomj** [comment]
Added more or less the whole _window hook_ set of features on a separate Draft PR. I believe the first PR is easier to review and requires less design decisions so ti may be better to work on that first and then we can flesh out the second one (or whatever you prefer, I don't really mind).

**Comment by carrascomj** [comment]
I summarised some of the decisions discussed here and in the corresponding PR [on the wiki](https://github.com/leftwm/leftwm/wiki/Config#window-rules). It is a bit verbose but I hope it is more or less clear.
