### ISSUE TITLE
Intellij pop-up breaks tile mode

### ISSUE THREAD

**Issue by lkadalski** [leftwm/leftwm#488]
**Describe the bug**
I'm using Intellij to work on Java projects. The unwanted situation is when I have two Intellij instances open at the same workspace and trigger popup window in one on them(rename a file). Then parent Intellij of that pop-up is taking whole screen and ignores the other (tiled) one. Even If I move the infected intellij window to other workspaces and back it ignores tiled windows on that workspace. It behaves like it is the only one tile window in workspace. I tried to move it to floating mode and back but once moved to floating mode it stays floated also. 
I have a feeling that leftwm mark parent intellij as pop-up, but I can't confirm.
Other programs work as expected. 

**To Reproduce**
1. Open Two instances of Intellij on one workspace
2. In one of the instances use pop-up window for instance: R click on a file ->Refactor -> Rename file. 
3. Pop-up shows and parent intellij is behaving like it's only one tile in workspace(error)
4. When tried to move to floating mode(it's working) then cannot return to tiled mode.(2nd error)

**Expected behavior**
After triggering pop-up, two instances of intellij are visible as two tile windows in the same workspace. Parent Intellij of pop-up acts as normal tile window. It can be moved to other workspaces as tiled one and it's recognized by leftwm as tiled one.
It can be change freely to flaoting mode and back to tiled one.  

**Environment:**
 - ArcoLinux
 - Output of `leftwm-check`:
 ```
 :: LeftWM version: 0.2.8
:: LeftWM git hash: 3c80a4a
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
```

Do you need any other information?

**Comment by hertg** [comment]
I planned on opening the exact same issue :smile:. I did a little research ahead to find out if it's something I could address with a PR myself. I had the exact same issue in dwm and it seems to stem from something that JetBrains messed up. I saw reports of the exact same issue for WebStorm, another JetBrains product.

Here are some resources I found:

- [Prevent my IDE to become floating in Awesome WM](https://superuser.com/questions/999486/prevent-my-ide-to-become-floating-in-awesome-wm) (superuser.com)
- [[DWM] Java App put itself in floating mode when child window opens.](https://www.reddit.com/r/suckless/comments/k4j89d/dwm_java_app_put_itself_in_floating_mode_when/) (reddit.com)
- [[DWM] [WebStorm][JetBrains] Webstorm window becomes floating mode when opening dialog boxes](https://www.reddit.com/r/suckless/comments/k67tso/dwm_webstormjetbrains_webstorm_window_becomes/) (reddit.com)\
  => [Here is the patch they came up with for dwm](https://github.com/Aram1d/dwm-6.2/commit/f47c3c83257eed490c6aaf876fbb67b2ddb8b62c)
- [Can not focus IntelliJ IDEs windows](https://github.com/awesomeWM/awesome/issues/889) - Issue for the same problem in AwesomeWM (github.com)

If we want to patch that in LeftWM, which would be really great, it probably requires implementing an exceptional behavior just for IntelliJ. While it is a bit annoying and might unnecessarily bloat up the code, it seems like JetBrains doesn't really care about the problem enough to fix it themselves. At least that's what I gather from the last comments [here](https://youtrack.jetbrains.com/issue/IDEA-155759), which they never addressed.

I just quickly read through the linked sites but didn't dig deeper. The relevant source code to implement such an exceptional behavior in LeftWM might be here:

https://github.com/leftwm/leftwm/blob/0908dda5b30079cdbff2f77b6996c3dcb9669245/src/display_servers/xlib_display_server/event_translate_property_notify.rs#L18-L29

With the current way IntelliJ behaves, I just don't open more than one instance of the IDE unnecessarily in order to avoid the issue. If I need to have more than one instance open, which can happen sometime when working with two projects that interact with each other, I just always put everything in floating mode to "avoid" the issue. But that really is a suboptimal "solution" and I'd love to see a fix for this issue, so I can open more than one tiled IntelliJ instance with LeftWM :)

**Comment by lkadalski** [comment]
Great research @hertg :+1: My bad I didn't do the same :) 
Your sub-optimal solution, works ;) But I'd love to do sth about this anyway.
I will take deeper look into `leftwm` myself.

**Comment by lkadalski** [comment]
I can't run leftwm from build becasue `ERROR: another window manager is already running`.
Even If I'm running xfce.  Any ideas?

**Comment by lkadalski** [comment]
If I logout and try running leftwm in tty I have `"Null pointer in display"`

**Comment by hertg** [comment]
> My bad I didn't do the same :)

Not at all. I should have opened the issue earlier tbh.
If you'd have waited, like I did, we'd both be doing the same research without knowing of each other :wink: 

> If I logout and try running leftwm in tty I have "Null pointer in display"

Yeah, I had similar issues actually. I ended up either running LeftWM in [Xephyr](https://wiki.archlinux.org/title/Xephyr) or running my local LeftWM directly. If you uninstall your current LeftWM installation and then follow [these steps](https://github.com/leftwm/leftwm#optional-development-installation), you can develop directly on LeftWM and then just run a `cargo build --release` followed by <kbd>Super + Shift + R</kbd>. To apply your local changes in your current Xsession. Just be aware that if you mess up, your current WM will stop working, because you are changing it directly. :stuck_out_tongue:

**Comment by lkadalski** [comment]
Ok I'm in @hertg one more question, where are logs stored? I don't see any clue in `/var/log/`

**Comment by hertg** [comment]
> Ok I'm in @hertg one more question, where are logs stored? I don't see any clue in `/var/log/`

Right, I forgot, I struggled with that question too. What I ended up doing if I wanted to see the console output was
- Open another tty
- Run startx
- Open a terminal
- Run leftwm from the terminal
- You should now see the output in the terminal directly

I'm new to the project myself, so that's why my solution is so hacky. Someone more experienced in the project should be able to assist and answer your questions better.

Btw. We have a Discord since a few days, but there aren't a lot of people yet. It might be better suited for quick questions unrelated to the github issue.

**Comment by lkadalski** [comment]
I'm debugging it now. It looks like I found a quick-fix for that.
We have to ensure that window_type is Normal not a Dialog.
I'm not sure is it expected? What kind of Normal window(programs) should be transient to some other window?
Lemme prepare PR

**Comment by lkadalski** [comment]
Fixed with https://github.com/leftwm/leftwm/pull/491 :rocket:
