### ISSUE TITLE
rename IncreaseMainWidth to IncreaseMainSize

### ISSUE THREAD

**Issue by dopelDev** [leftwm/leftwm#545]
hello I have not found a way to modify the height of the windows.
Something similar to IncreaseMainWidth.
Would there be some way

**Comment by kid** [comment]
At least on `MainAndHorizontalStack`, `IncreaseMainWidth` actually changes the height of the main window, so I'm not sure anything is required :thinking:

**Comment by hertg** [comment]
Not sure what this issue is exactly about?
We could rename the `IncreaseMainWidth` to `IncreaseMainSize`, I would be in favor of that. Then we can rename this issue to "rename IncreaseMainWidth to IncreaseMainSize". What do you think @VuiMuich?
Regarding the last comment for window resizing in non-main windows, that is tracked in #649
