### ISSUE TITLE
workpace_magin and margin for single window on workspace

### ISSUE THREAD

**Issue by patrikha** [leftwm/leftwm#581]
Setting workspace_margin = 0 and margin = 10 will create a 10px gap around the single and only window. Not sure if this is by design but it would be nice if there is only one window then it would fill the entire workspace, then when creating additional windows the margin of 10 would apply around each window and also applying the workspace_margin of defined, (like i3-gaps).
Today they append to each other.
Using version 0.2.10

**Comment by stevensonmt** [comment]
I think this could be implemented without too much difficulty (famous last words) but I'm not sure the juice is worth the squeeze. If i3-gaps only applies margins when there is more than one window, that seems counterintuitive to me. If you define a margin settings for windows, you should expect that margin to be applied to all windows equally. I think you might be able to achieve a sort of toggle for this with a layout that ignores window margins all together. Giving it a name like "MarginLess" would make it clear what the expected behavior is. You could switch layouts when you open more than one window.

**Comment by VuiMuich** [comment]
A relatively simple workaround is to add a keybind `leftwm comman "SetLayout Monocle" "SetMarginMultiplier 0"` and to reverse it replace the Next/Prev Layout bind with `leftwm command "NextLayout" "SetMarginMultiplier 1"`/`leftwm command "PreviousLayout" "SetMarginMultiplier 1"`

**Comment by patrikha** [comment]
OK thanks, closing...
