### ISSUE TITLE
Popup window - pamac-all - mint-stick-git

### ISSUE THREAD

**Issue by arcolinuxz** [leftwm/leftwm#614]
**Describe the bug**
Going to preferences in Pamac gives us  a very small window - was unable to resize it.
Solved it by going super + F = fullscreen

**To Reproduce**
Arch Linux or ArcoLinux and install pamac-all - open up preferences

**Expected behavior**
a bit bigger please

**Screenshots**
![Screenshot from 2021-12-07 20-57-06](https://user-images.githubusercontent.com/36679406/145097696-7e827b18-94b3-4759-80da-18bb94c39754.png)

**Environment:**
 - OS/Distro: ArcoLinux
 - Output of `leftwm-check`
 `[erik@ArcoLinux-IsoBuilder ~]$ leftwm-check
:: LeftWM version: 0.2.10
:: LeftWM git hash: 30b331d
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
[erik@ArcoLinux-IsoBuilder ~]$`

**Additional context**
new package build today on Arch Linux - leftwm - 1:0.2.10-1 based on your tags

**Comment by arcolinuxz** [comment]
Had some issues with mintstick as well.

The problem there is the popup to get root permissions.

Sometimes the input for the root password is not available.

Mintstick - r221-e7b1893-1

I have seen you guys have been working on a solution for these windows.
I though I report already this.

![Screenshot from 2021-12-07 21-02-33](https://user-images.githubusercontent.com/36679406/145098176-dd19f90f-d331-4abe-9259-4a2e9b8d9af1.png)

**Comment by AethanFoot** [comment]
The one with pamac is something we are looking to fix, if the dialog seems too small we can make it bigger. The authenticate one from a small testing seems the polkit gui seems to give a smaller size with a configure request which then gets resized once an update loop is called to the min size which allows the bar to appear. A lot of these issues are because the sizes and information we are sent isn't ideal, these are generally going to be easy to fix. 

The mintstick one with the main window be small and non-resizable should be raised with them as they are setting the min and max size to the same (and too small and continuously changing) which [indicates the window should be non-resizable](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#NORESIZE). We can address this but means we would need to ignore all of their property notifies as the "fixed size" is continuously changing depending on the window state.

**Comment by VentGrey** [comment]
I found that a quick focus change can trigger the polkit password prompt, just focus another window or move the mouse around to make it show. It's a workaround until things get fixed :)

**Comment by arcolinuxz** [comment]
noticed that too - odd behavior lol

**Comment by arcolinuxz** [comment]
![grub-customizer](https://user-images.githubusercontent.com/36679406/145201876-510b0087-7e21-470e-8f97-f716a2687e65.png)
I will add other examples so you have test material
grub-customizer popup

**Comment by AethanFoot** [comment]
Can you test #615, from what I can tell most of these are fixed. There still is the issue of mintstick resizing itself when the state changes, but is seems much better.

**Comment by VentGrey** [comment]
I'm testing on Debian stable, `synaptic-pkexec` dialog issues are gone with #615.

**Comment by arcolinuxz** [comment]
Meld is now behaving differently.
It is tiling over the second screen
![Screenshot from 2021-12-09 08-57-38](https://user-images.githubusercontent.com/36679406/145356723-b1f5bfab-958e-4279-9a5c-2a4c5f6528b6.png)

**Comment by arcolinuxz** [comment]
Can you share a link to a pkgbuild where we can use your dialog branch (Arch Linux)?

**Comment by AethanFoot** [comment]
[PKGBUILD.txt](https://github.com/leftwm/leftwm/files/7684545/PKGBUILD.txt)
Is this what you meant? Had to share as .txt as github won't take it as just PKGBUILD.

**Comment by AethanFoot** [comment]
Also is the meld issue on master or #615?

**Comment by arcolinuxz** [comment]
Mintstick
![ArcoLinux-2021-12-14_18-23](https://user-images.githubusercontent.com/36679406/146048319-4368816a-5199-4e39-ab2c-c609e5ad984f.jpg)

Pamac

![ArcoLinux-2021-12-14_18-25](https://user-images.githubusercontent.com/36679406/146048868-47eae2bf-c8e6-42e9-9b5a-ccc237ac15ae.jpg)

All improved

using my own package - Arch Linux git package was not up to date

![ArcoLinux-2021-12-14_18-27](https://user-images.githubusercontent.com/36679406/146049042-825fa3f4-3f98-4674-ae5d-e51657f21bc7.jpg)
