### ISSUE TITLE
Future Plans 

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [leftwm/leftwm#66]
It would be cool if your team set up a roadmap or set milestones so the public could see where leftwm wants to go. Awesome project!

**Comment by hertg** [comment]
Specifying roadmaps and milestones can be pretty hard in open source projects. I do agree that it would be pretty great for users to see the progress and what features they can expect in the next release... 

But, which features get implemented really depends on if there is a dev willing to take on a pre-existing issue/request. A lot of times new features will be added via PRs without them being planned too far ahead. Because of this, there really isn't an easy way to exactly specify the releases, when they will release, and what they will contain. Also, the current practice of this kind of "rolling release" also has the benefit of moving the project forward without too much of a management overhead. I personally really like that agility this project seems to have, it's something that actually really motivates me to contribute.

That being said, we are currently in the process of cleaning up the issues, remove duplicates, add better titles and labelling them. I think this way a very basic kind of "roadmap" will already be provided when users open the issues and PR tabs. Of course, it won't be as specific as an exact roadmap, and it won't really provide you with any time estimates for the next releases, but you also can't really expect that from an open source project which is made by people that come and go, and only work on it in their free-time :smile: 

I completely share the wish for some overview though, that's why I opened #519. I hope this will provide a clearer overview for users, and especially for new contributors :)

**Comment by hertg** [comment]
> In this issue we could keep track wich issues we'd like to see solved, bugs fixed and features implemented before the next version bump. It's a bit 'milestones light'.

That sounds great! But if bugs/features are already being tracked in this new issue, wouldn't creating a github milestone and adding said issues/PRs to it be exactly the same? It might actually be easier to track it via github milestone, because you can just assign the milestone directly on the issue/PR, without updating the "version tracking issue". :thinking:

---

Something that would be really great too, is to create a "Github Release" for each tag and adding release notes to it. Currently the Github tags only tell the user that all those versions exist, they don't tell what those versions contain in terms of bugfixes and new features.

**Comment by VuiMuich** [comment]
It's just milestone felt too big for me.
0.2.x->0.3.0 feels milestone worthy imo. 
But sure the automation involved with milestones is nice.
So we could do milestones for minor updates as well if you all like.

I agree, the the release tags could use a bit more information. If that's possible now, I could copy the change log sections to them for now.

**Comment by VuiMuich** [comment]
Unless we want a (pinned?) issue tracking longterm goals, I'd deem this one resolved with milestones for the next version bump.

BTW: I guess hertg was right, with his reasonig, that keeping both the issue and the milestone keeping track is unreasonable redunancy. I'd like to try to use the issue for `0.2.11` to only track of user wishes for this version bump and use the milestone to track the actual progress.
