### ISSUE TITLE
Allow the same label in multiple tags

### ISSUE THREAD

**Issue by il-mich** [leftwm/leftwm#68]
When two tags have the same character in the "tags" section of leftwm/config.toml they are treated as one even if the number corresponding is different.
In my case two tags were named "I": number 1 and 4, this made the wm show the same windows in tag 1 and in tag 4.
Moving windows from and to tags 1:4 works as usual, one window in [eg] tag 2 is then shown in both 1 and 4, a window shown in 1 and 4 is one when moved to any other tag.

**Comment by hertg** [comment]
This one seems easy enough to fix, I could take that on.

My proposal to fix this would be to change the `Tag.id` to be a unique integer (`u8`?), and create a new attribute called `label` where the tag-name should be stored.

eg.
```rust
pub struct Tag {
    pub id: u8,
    pub label: String,
    pub hidden: bool,
    pub layout: Layout,
    pub main_width_percentage: u8,
    pub flipped_horizontal: bool,
    pub flipped_vertical: bool,
    pub layout_rotation: usize,
}
```

The `id` would basically be the index of the tag in the configured array. This way each tag will have a unique identifier.
Also, this would simplify some code where Tag IDs are compared, because we no longer have to compare strings, just integers.

@VuiMuich @AethanFoot 
What do you think of that idea? It will probably require touching a lot of source code, because the data type changes and the Tag ID is accessed / compared in a lot of places. But I don't mind that, because I want to get familiar with the source code anyway.

**Comment by hertg** [comment]
Also @AethanFoot, could you rename this issue to something like "Allow the same label in multiple tags"

**Comment by hertg** [comment]
I looked into it a bit and it eems like changing that isn't as straightforward as I imagined. I'm still willing to go for it though :stuck_out_tongue:

There are some weird edge cases that require me to change more things than expected. There is the hidden `NSP` tag for scratchpads, and there is the functionality that new tags are added "on-the-fly" if the amount of workspaces exceeds the amount of tags, so I'll have to take those functions into consideration. 

But as I've said, I should be able to handle that, just wanted to give a heads up that it requires some more time and some more code changes than I anticipated :)
