### ISSUE TITLE
Can't have top margin on polybar

### ISSUE THREAD

**Issue by Trek3** [leftwm/leftwm#69]
So apparently left will automatically set polybar `y-coordinate` to 0. The only way to have some kind of margin on top is to set polybar `override-redirect` to `true`. The problem with this solution is that the bar is "ignored" and the windows spawn over the bar. Is there a way to solve this?

This is with `override-redirect` to `false`, even if `offset-y = 10%` (and in fact, as you can see, the windows spawn as if the bar was in fact drawn lower in the screen)

![2020-01-26-152158_1917x1053_scrot](https://user-images.githubusercontent.com/4323569/73136623-d3e7cf80-404f-11ea-99d1-a92f605cd4e7.png)

This is with `override-redirect = true`.

![2020-01-26-152239_1919x1078_scrot](https://user-images.githubusercontent.com/4323569/73136632-e5c97280-404f-11ea-9c8a-8ad7298f5d68.png)

**Comment by lex148** [comment]
@Trek3, its been a little while and wanted to give you an update on this one. Work has been super busy the last two weeks so i haven't been able to really dig into this one yet, but I do have a little info. It appears polybar is correctly sending bar sizing info to leftwm, but its a little different than what I expected and different from what other bars such as lemonbar and xmbar are sending. I want to be careful with this fix as I want to make sure I don't break other bars. 

I have updated my theme that I use on a daily basis and your problem is now my problem. 

I'm hoping to get this one fix soon

-Lex


love you theme by BTW

**Comment by lex148** [comment]
This is now fixed in the latest of master

**Comment by Trek3** [comment]
Sorry for the late reply, and thanks for solving the issue. One question though: how can I increase the margin between the bar and the windows? Because now they're almost touching, I wanted the same margin that you set in the config.toml instead. Thank you!

**Comment by lex148** [comment]
Just pushed another small change for this one. 

If you get latest the following should work in your ploybar config

[global/wm]
margin-bottom = 100
