### ISSUE TITLE
Epitaph is rebooting me to my login manager?

### ISSUE THREAD

**Issue by MrCockles** [leftwm/leftwm#691]
**Describe the bug**
I changed my leftwm theme to Epitaph while using Awesomewm, and received no errors from the terminal. I then switch to leftwm via sddm, my wallpaper loads briefly, then the screen goes black, and starts me back in sddm. this issue seems to be from the theme, I can change my theme back to candy and leftwm runs just fine. 

**To Reproduce**
1. open terminal in another wm
2. run: leftwm-theme apply "Epitaph"
3. exit to sddm 
4. login to leftwm
5. reboots to sddm

**Expected behavior**
since there weren't any errors from my terminal that the theme would load properly, I'm not sure what else to put here for this issue.

**Screenshots**
![20220130_143227](https://user-images.githubusercontent.com/40811670/151716766-2573b445-bd59-4e7f-9b6a-274190c93c40.jpg)
![20220130_143223](https://user-images.githubusercontent.com/40811670/151716784-5c525ede-5e6c-464c-8f11-38c098a189e3.jpg)
![20220130_143224](https://user-images.githubusercontent.com/40811670/151716787-b5cff85d-0b01-4cee-8743-f9191b9d8395.jpg)

**Environment:**
 - OS/Distro: Arco
 - Output of `leftwm-check`

![ArcoLinux-2022-01-30-1643574446_screenshot_1920x1080](https://user-images.githubusercontent.com/40811670/151716454-044ab4df-e3ce-4a4d-9adb-f7c7bf0cba72.jpg)

**Additional context**

**Comment by mautamu** [comment]
Does LeftWM have a way of checking if it's incompatible with a theme? 

@MrCockles do you mind recompiling with --features journald and seeing if there are any logs in journalctl -u leftwm-worker ?

**Comment by mautamu** [comment]
Tagging @VentGrey

**Comment by VentGrey** [comment]
Ah I see why this is failing then. The same [Epitaph Wiki](https://github.com/VentGrey/Epitaph/wiki) states that some steps are needed to get the theme working first, as the default configuration is made with lemonbar it requires some modules to be compiled to ensure performance. 

I placed this extra steps on the wiki because `leftwm-theme` still does not have `pre` and `post` install instructions (tracked in #292). 

Epitaph rebooting you to your login manager is probably because the `camel` script exits with an error and somehow it kills the X session. If you have further issues or need help with the theme please open an issue [here instead](https://github.com/VentGrey/Epitaph/issues) as my theme is not part of the official leftwm assets :)

**Comment by hertg** [comment]
Closing because it's a community theme issue and should probably be tracked there
