### ISSUE TITLE
Issues regarding main width percentage and `LeftWiderRightStack` layout

### ISSUE THREAD

**Issue by zvolin** [leftwm/leftwm#762]
**Describe the bug**
So there are two problems that I'm aware of.

First one:
Main window width percentage set for `LeftWiderRightStack` layout and it's sibling does not persist tag change when using `LayoutMode::Workspace`.

When using `LayoutMode::Workspace` and switching layout to `LeftWiderRightStack`, main window's width is set to 75% . When you then switch to a different tag, all tags will now have equal windows (50%) even tho the layout hasn't changed.

Second one:
Custom main window width percentage behavior is not consistent when switching layouts.

After increasing/decreasing main window width, switching layout to any other that supports main window resizing keeps my overridden main window width. Switching to and from to the layouts that don't support main window resizing doesn't make my setting forgotten when switching back. However switching to and from `LeftWiderRightStack` and it's sibling behaves like for layouts not supporting main resizing but this layout allows resizing.
After increasing/decreasing main window width when on `LeftWiderRightStack` and then switching to other layout however keeps the width change but it looks like the width change was done relative to the base 50% width, not the `LeftWiderRightStack`'s 75%. So e.g. if you decrease main window width from 75% to 50% on `LeftWiderRightStack` and then switch to `MainAndVertStack`, the main window width will be 25%, not 50% as I'd expect.

**Solutions**
I see two possible ways to make this behavior consistent.

First one:
When switching to another layout, always determine whether user has changed `main width` by checking if current main width equals layout's default main width. If user has default main width, then set workspace's main width to the default value of layout. If user has changed main width, then always keep it, even for `LeftWiderRightStack` and it's sibling.

Second one:
Disallow changing main width percentage for `LeftWiderRightStack` and it's sibling and ignore value of workspace's main width within layout's `update` method.

First solution makes `LeftWiderRightStack` basically a `MainAndVertStack` with starting default main width set to 75%, but after changing main width anywhere those two will be identical.

Second solution much more separates `LeftWiderRightStack` from `MainAndVertStack` and makes it kinda a static, predefined layout.

I'm not sure which one I like more but I'd probably favor the latter as the first feels like killing this layout, one could just resize `MainAndVertStack` and has the exact same behavior afterwards. Kind of shame as I already implemented the former while digging this topic, but I'm okay with implementing the second one also :upside_down_face: 

**Environment:**
 - OS/Distro: Arch 5.17.5-zen
 - Output of `leftwm-check`
 
```
❯ leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: c0fcf84
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by hertg** [comment]
Hi, thanks for your submission and the PR you opened. Nice and clear issue formulation btw. :1st_place_medal: 
I didn't dig very deep into the solutions you proposed yet, but on the first glance your ideas/submission look good.

Just wanted to let you know that I'm currently working on a new layout system which might touch (some of) the problems you mention. I have been working on the layouts for a while and I think I'm nearing the finish line. So i wanted to dump that here as background information:

---

With my current vision, layouts will become a bit more dynamic, in the sense that layouts could potentially be formulated in terms of configuration (see [this example](https://github.com/leftwm/leftwm-layouts/blob/227a9233eaab1909cce423adad7dd337408b20cc/leftwm-layouts/src/layouts/default.ron)).

This idea might touch your issues in the following way:
Right now, layouts are statically/programmatically defined. Each tag/workspace (depending on layout-mode) is set to a certain layout and "layout modifiers" are stored directly on the workspace/tag struct (eg. `tag.main_width_percentage`, `tag.layout_rotation`) and so on.

My current vision is to switch to a [`LayoutDefinition`](https://github.com/leftwm/leftwm-layouts/blob/227a9233eaab1909cce423adad7dd337408b20cc/leftwm-layouts/src/layouts/layout_definition.rs#L20-L96) struct that defines the layout itself and contains all those "layout modifiers" in it, as they basically also are what defines a certain layout (see `MainAndVertStack` vs. `LeftWiderRightStack`). 

Each tag/workspace then holds an array of self-contained `LayoutDefinitions` (the layouts you can switch through) where one of the layouts in the array is the currently applied one. The user can make changes to the layout at runtime (eg. by increasing `main_window_size` with a keybind) and with that directly change the `LayoutDefinition` stored on the tag/workspace.

This would solve your issue where a users runtime changes would not persist, or apply to unrelated layouts, because every runtime change would change the definition of the layout itself, instead of merely being an applied "layout modifier". The predefined LeftWM layouts would then just be the default layout configuration that is loaded on startup, but every aspect of the layout could be changed at runtime by the user. The coolest thing about that idea IMO is that layouts can be defined completely in terms of configuration (as in [the example](https://github.com/leftwm/leftwm-layouts/blob/227a9233eaab1909cce423adad7dd337408b20cc/leftwm-layouts/src/layouts/default.ron)) which means that users could create their own layouts, or change the defaults of "layout modifiers" to their preferences, completely through configuration.

---

This is just my current state where I **think** the layout-system could go, but I wanted to ask for opinions of other devs and the users first, and I haven't done that yet :smile:. I'll probably do that in Discord, so we don't pollute your issue/PR with unrelated discussion.
