### ISSUE TITLE
scrolling redraw is a bit jankey for x11 compositor

### ISSUE THREAD

**Issue by gilescope** [leftwm/leftwm#769]
I don't know why but browsers under this wm seem not to scroll smoothly. There's a bit of not quite tearing but judder. It's odd because you would think rust could be super speedy. Maybe I am behind the times and should be moving to wayland compositor?

**Comment by gilescope** [comment]
version wise I am using the latest packaged by nixos unstable.

**Comment by VuiMuich** [comment]
Most certainly this is more related to the key-refresh of X11.
I believe DistroTube had a video on this topic. I'll see if I can find it later.

**Comment by hertg** [comment]
I haven't heard about this issue from others yet.
Is this an issue that we can reproduce and actually address in LeftWM? My assumption is that the underlying problem is not caused by LeftWM specifically. I'm closing it for now on that basis. Please reopen if I'm wrong :)

**Comment by VuiMuich** [comment]
Welcome adventurer @Canvis-Me!

Gnome (or any other "big DE") may come with its own anti tearing measure in place. To test if it is really a `leftwm` issue it would be advisable to test, if the issue is reproducible in another minimal WM as well. `bspwm` or `dwm` are usually good for such tests, as they also come with minimal pre-configuration.

Often it helps to set a config option for X11 like this:
```sh
bat /etc/X11/xorg.conf.d/20-intel.conf
───────┬─────────────────────────────────────────
       │ File: /etc/X11/xorg.conf.d/20-intel.conf
───────┼─────────────────────────────────────────
   1   │ Section "Device"
   2   │   Identifier "Intel Graphics"
   3   │   Driver "intel"
   4   │   Option "TearFree" "true"
   5   │ EndSection
───────┴─────────────────────────────────────────
```
Details might vary on your graphics card.

I tried to play a tearing test video on my machine with both, `ffplay` and `mpv` (well aware that both use the ffmpet decoder, but I wanted to be sure to test as minimal as possible and on the otherhand that it is not simply mpv that adds some render lag). But to be absolutely certain, can you share your video source so I can test with exactly the same footage?

**Comment by Canvis-Me** [comment]
Thanks for your reply, I tested on `dwm` too, and it turned out the same problem as `leftwm`. So the problem was less relative to `leftwm`, it may be something else about my local config. My video card is NVIDIA, I will try `xorg.conf` option later.

Here's my test video file:

[magiclen.org_tearing-test-fhd-60.tar.gz](https://github.com/leftwm/leftwm/files/9748183/magiclen.org_tearing-test-fhd-60.tar.gz)

**Comment by VuiMuich** [comment]
Vid looks good as well on my side, thanks.

I guess nvidia as whole adventure on its own right. I picked up the keyword `ForceFullPipelineComposition` in context of vsync before, but I have no real experience with nvidia in linux.

**Comment by Canvis-Me** [comment]
Yeah, I added `ForceFullCompositionPipeline=On` to the config file, and the video played well now. Solved my problem.
