### ISSUE TITLE
Polybar showing polybar window in virtual desktop

### ISSUE THREAD

**Issue by epicgamer256705** [leftwm/leftwm#770]
When I use polybar there is an annoying bug where in desktop 1 it shows a window open because that is where polybar is being opened from.

**Comment by VuiMuich** [comment]
What window type is your polybar? It would be `dock` ideally.

**Comment by epicgamer256705** [comment]
How do I check the window type?

**Comment by VuiMuich** [comment]
The most common way would be to use `xprop`.
You run it from terminal and get a crosshair to click on the desired window. Then find the line with `_NET_WINDOW_TYPE` in the output.

**Comment by epicgamer256705** [comment]
How do I change it to dock?

**Comment by epicgamer256705** [comment]
It is set to dock

**Comment by hertg** [comment]
Is the bug here that `wmctrl -l` should not return polybar in the list of managed windows?

**Comment by VuiMuich** [comment]
No, if I get OP right the issue is that an empty tag 1 is indicated as `busy` by the presence of the polybar window.

`wmctrl -l` was used by me just to confirm that the `dock` windows indeed get spawned on that tag where the`SoftReload` was issued from (or 1 after session start or `HardReload` ofc)

Closing this as this most certainly is just an improper polybar config.
