### ISSUE TITLE
Add tabbed layout similar to SwayWM

### ISSUE THREAD

**Issue by moghaazi** [leftwm/leftwm#776]
![image](https://user-images.githubusercontent.com/49992538/173241925-9364befe-8bbb-47b7-b21f-c937791bd710.png)

**Comment by VuiMuich** [comment]
`LeftWM` has no native feature to Render the tabs, as we explicitly keep bars, menus out of the core project in order to stay close to the Unix philosophy.

Our 'one thing' is 'manage windows'. `loading themes` is already stretching it, but I believe there is no feasible other way to handle window borders and that's basically everything the theme is doing 'internaly'.

This requested feature though, might be achieved with third party applications like `rofi` or `eww` for example and the monocle layout.

Maybe I can come up with some example config in the coming days.

**Comment by jlvihv** [comment]
> Maybe I can come up with some example config in the coming days.

Could you please help with a sample configuration like this?

**Comment by VuiMuich** [comment]
To be fair, I forgot about this requiset, but OP didn't seem to eager to come back to this converstation either.

At this point I just can give you some directions, as I don't have the time to  workout a full setup. An easy solution might be `rofi -show windowcd` but it does not provide a constant tabbar.
Such a bar could be done as a widget in `eww` requirirg some scripting and `wmctrl` and [`jo`](https://github.com/jpmens/jo):
1. use `wmctrl -d | grep '*' | cut -f 1 -d " "` to get the  current tag as numerical ID
2. use `wmctrl -l` and `awk` to filter for windows only on the current tag
3. use `jo` to cronvert the above output into a JSON input for `eww` (firs field will be window id, third the window name)
4. create some widget that has buttons with lable text from the windownam field and on click it calls `wmctrl -i -a <win-id>`
5. the widget needs to reserve space with `:reserve (struts :side "top" :distance "55px")`, distance being you status bar + tab bar hights
6. try to set a hook, that this widget is only opened on the monocle layout and when more then one window is on the tag
7. post it on the eww repo and r/unixporn as this will be awesome :wink:
