### ISSUE TITLE
Naming tags after specifying dimensions

### ISSUE THREAD

**Issue by xircon** [leftwm/leftwm#88]
To solve a problem with the systray (I couldn't click on it), I reserved space for it and added to polybar:
```
wm-restack = i3
override-redirect = true
```
Now I can't name tags, but the systray works.  This is what I have, what have I done wrong?
```
modkey = "Mod4"
Alt = "Mod1"

[[workspaces]]
y = 30
x = 0
height = 870
width = 1600

tags = ["Term", "Emacs", "Web", "Chat", "5", "6", "7", "8", "FS"]
```

**Comment by lex148** [comment]
xircon,

Sorry it has taken a while for me to get back to you. This month has been a bit crazy. Alt is not a valid option to add to your config. If you comment out that line it should work. I should probably add a way to clearly inform the user when something like this happens.

**Comment by xircon** [comment]
Completely understand.  Tried it, but it doesn't make any difference.  Keep safe.

**Comment by jqfeld** [comment]
@xircon Did you set the y coordinate to 30 because with the `override-redirect = true` the polybar overlaps your application windows? I had the same problem and putting the override option under mainbar0 solved it for me (even thought I don't quite understand why as I don't have any experience with polybar):
```INI
[bar/mainbar0]
inherit = bar/barbase
modules-left = workspace0
tray-position = right
tray-padding = 2
override-redirect = true
```
Maybe this way you don't need to specify the dimensions manually?
