### ISSUE TITLE
close window leaving zombies

### ISSUE THREAD

**Issue by Zenick00** [leftwm/leftwm#89]
closing windows leaves program running as defunct until
restart of leftwm ether by logging or mod+shift+r.

**Comment by superobertking** [comment]
I also met this problem. This is because the `Command` created [here](https://github.com/leftwm/leftwm/blob/ee5c8dd5de2c65e0f96bc247a6246b498251fc54/src/handlers/command_handler.rs#L38) was never `wait`ed.

[Alacritty](https://github.com/alacritty/alacritty/) solved this problem by adding an additional fork in `pre_exec` and `wait` for the child process, see [code](https://github.com/alacritty/alacritty/blob/0f82817c03ebb0f26f3423bbcd48e527ab138cc2/alacritty_terminal/src/util.rs#L58-L72) and [git blame](https://github.com/alacritty/alacritty/blame/0f82817c03ebb0f26f3423bbcd48e527ab138cc2/alacritty_terminal/src/util.rs#L58-L72).

Leftwm could probably solve this problem in the same way.

**Comment by superobertking** [comment]
I guess a better way to implement this is by using `SIGCHLD` just like what GNOME’s GLib does: [ref](https://gitlab.gnome.org/GNOME/glib/-/blob/730a75fc8e8271c38fbd5363d1f77a00876b9ddc/glib/gmain.c#L5229-5236).

I have a WIP fork and hopefully I could finish the PoC soon.

**Comment by jfgodoy** [comment]
I just curious, I'm noob in this subjet. Why do you prefer the SIGCHLD solution instead of the additional fork?. IMHO the addional fork is more simple.

**Comment by superobertking** [comment]
@jfgodoy Sorry for the late reply.

I would prefer a feeling of being able to mange the subprocesses spawned by this process, though it does not give additional functionality for now.

And I feel having an additional forking might incur additional overhead (cloning a process needs to copy a lot of things even with CoW)<sup>[[1]]</sup>.

Actually both are ok, and I couldn't tell if there's any performance difference between them. For day to day use on a modern computer, there should not have a big difference.

[1]: https://dl.acm.org/doi/10.1145/3317550.3321435

**Comment by jfgodoy** [comment]
thanks @superobertking for the reply. Your previous comments allowed me to fix the same bug on my own proyect, but I chose the double fork option for brevity. Thank you!
